
name: Leaders hackathon backend deployment

on:
  push:
    branches: [ main ]

jobs:        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run tests
        run: go mod tidy && go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build and run docker containers via ssh
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          first_ssh: cd backend/ && git checkout main && git pull
          last_ssh: docker-compose build && docker-compose stop && docker rm $(docker ps -aq) && docker-compose up -d
