
name: Leaders hackathon backend deployment

on:
  push:
    branches: [ main ]

jobs:        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - run: go mod tidy && go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and run docker containers via ssh
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASS }}
          scp: |
            ./ => ~/backend/
          last_ssh: |
            cd ~/backend && docker compose build && docker compose stop && docker rm $(docker ps -aq) && docker compose up -d
